# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2052641edd862d1144f7ad744b0790410f225c1beebe70e38792db9dec67f8f2bd23e1ca31e0570647a486fe4e84b0b9c58374ad5e84c9b507393cdbe6d2498

test:
  secret_key_base: b2a50b847b9578fc50757fc7350f570ce82a92050452a164197e54d068cb00b7f393923e8e260c97484eef4e1181b945bd126ffb44a89fcb194a3ecab4de0539

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
